services:
  dns-guard:
    image: nmisha/antizapret-vpn-dns-guard:6.0.12
    hostname: dns-guard.antizapret
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [ node.labels.location == local ]
    environment:
      DNS_GUARD_CONFIG: /config/config.json
      DNS_GUARD_RULES: /config/risk-domains.json
      DNS_GUARD_HTTP_ADDR: :8090
      DNS_GUARD_HTTP_TOKEN: change-me-dns-guard-api-token
      DNS_GUARD_STATE: /state/state.json
      # DNS_GUARD_QUERYLOG: /adguard/querylog.json
      DNS_GUARD_NOTIFICATION_URL: http://tgbot.antizapret:8081/risk-notifications
      DNS_GUARD_NOTIFICATION_TOKEN: change-me-risk-token
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - $PWD/config/adguard/work/data:/adguard:ro
      - $PWD/config-mine/dns-guard:/config:rw
      - $PWD/config-mine/dns-guard/state:/state:rw
