services:
  crowdsec:
#    cpus: "0.3"
#    mem_limit: 300m
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    hostname: crowdsec
    restart: always
    environment:
      TZ: "Europe/Moscow"
    # DISABLE_PARSERS: "crowdsecurity/whitelists"
      # COLLECTIONS: "crowdsecurity/linux crowdsecurity/iptables crowdsecurity/nginx-proxy-manager crowdsecurity/sshd LePresidente/adguardhome crowdsecurity/appsec-virtual-patching crowdsecurity/base-http-scenarios crowdsecurity/http-cve pserranoa/openvpn crowdsecurity/caddy LePresidente/authelia crowdsecurity/nginx crowdsecurity/wireguard"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/iptables crowdsecurity/sshd LePresidente/adguardhome crowdsecurity/appsec-virtual-patching crowdsecurity/base-http-scenarios crowdsecurity/http-cve pserranoa/openvpn crowdsecurity/caddy LePresidente/authelia crowdsecurity/wireguard"
      GID: "${GID-1000}"
    ports:
      - '127.0.0.1:8943:8080' ## We expose the LAPI 8080 via loopback for bouncers to connect
    volumes:
      - $PWD/config-mine/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      # - ./crowdsec/db:/var/lib/crowdsec/data/
      # - ./crowdsec/config:/etc/crowdsec/
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - $PWD/config-mine/crowdsec/custom_whitelist.yaml:/etc/crowdsec/parsers/s02-enrich/custom_whitelist.yaml

      - /etc/timezone:/etc/timezone:ro

      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/log/caddy:/var/log/caddy:ro
      - $PWD/config/openvpn/log:/var/log/openvpn:ro
      - /var/log:/var/log/host:ro

    deploy:
      mode: global
      endpoint_mode: dnsrr
    # network_mode: host
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_MODULE

#healthcheck:
#test: ["CMD", "cscli", "version"]
#start_period: 10s
#networks:
#crowdsec_net:
#ipv4_address: 172.21.0.11      

#    networks:
#      crowdsec:
#        ipv4_address: 172.20.0.4



    # networks:
      # dmz_network:
        # ipv4_address: 10.219.0.11

volumes:
  crowdsec-db:
  crowdsec-config:
