#!/usr/bin/env python3
"""Generate direct-routing (no VPN tunnel) rules from ../ip_checkers.txt.

Outputs (next to this script):
  exclude-hosts-custom.txt   ERE regexes -> config/antizapret/custom/exclude-hosts-custom.txt
  adguard-custom-rules.txt   @@ exceptions for domains still matched by include-hosts-dist.txt

Domains listed in the "# /^host$/" comment block of ip_checkers.txt are
treated as exact-host rules; every other ||domain^ entry matches subdomains too.
"""
import re
from pathlib import Path

here = Path(__file__).resolve().parent
src = here.parent / "ip_checkers.txt"
include_file = here.parent / "include-hosts-dist.txt"

domains, exact = [], set()
for line in src.read_text().splitlines():
    line = line.strip()
    m = re.fullmatch(r"\|\|([^\^]+)\^", line)
    if m:
        d = m.group(1).lower()
        if d not in domains:
            domains.append(d)
        continue
    m = re.fullmatch(r"#\s*/\^(.+)\$/", line)
    if m:
        exact.add(m.group(1).replace("\\.", "."))

lines = ["# Generated by gen.py from lists-mine/ip_checkers.txt. Do not edit by hand.",
         "# IP checkers that must NOT be routed through the VPN tunnel.",
         "# ERE, one per line. Exact-host rules are anchored, the rest also match subdomains."]
for d in sorted(domains, key=lambda x: (x not in exact, x)):
    esc = d.replace(".", r"\.")
    lines.append(f"^{esc}$" if d in exact else fr"(^|\.){esc}$")
(here / "exclude-hosts-custom.txt").write_text("\n".join(lines) + "\n")

include = {l.strip().lower() for l in include_file.read_text().splitlines()
           if l.strip() and not l.startswith("#")}

def include_match(d):
    parts = d.split(".")
    for i in range(len(parts)):
        s = ".".join(parts[i:])
        if s in include:
            return s

rules = ["! Generated by gen.py. Paste into AdGuard Home -> Filters -> Custom filtering rules.",
         "! Domains from ip_checkers.txt that include-hosts-dist.txt would still route via VPN."]
for d in domains:
    m = include_match(d)
    if m:
        rules.append(f"! {d} <- include entry '{m}'")
        for client in ("az-local", "az-world"):
            rules.append(f"@@||{d}^$dnsrewrite,client={client}")
(here / "adguard-custom-rules.txt").write_text("\n".join(rules) + "\n")

print(f"{len(domains)} domains, {len(exact)} exact, "
      f"{sum(1 for r in rules if r.startswith('@@'))} @@ rules")
