services:
  zerotier:
    image: zerotier/zerotier:latest #seedgou/zerotier
    container_name: "zerotier"
    network_mode: "host"
    restart: always
    volumes:
      # - ./config:/var/lib/zerotier-one
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config/zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
