services:
  iperf3:
    container_name: docker-iperf3
    restart: unless-stopped
    # networks:
    #   - iperf3
    ports:
      - '5201:5201'
    image: loganmarchione/docker-iperf3:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
# networks:
#   iperf3:

